### ISSUE TITLE
Can Docker and Docker Compose be used under the admin/deploy/ directory?

### ISSUE THREAD

**Issue by jitangshaobing** [YFGaia/dify-plus#1]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I tried several deployment methods, but none of them were successful.

**Comment by FamousMai** [comment]
Can you tell us how you run it? What is the error? 

We will provide a complete docker-compose method in the near future and notify you when the time comes

**Comment by jitangshaobing** [comment]
The default configuration file for admin seems to use MySQL, but other applications default to PostgreSQL, and the SQL initialization file could not be found.

**Comment by jitangshaobing** [comment]
’ll be waiting for the complete Docker Compose deployment steps to be released. Thank you!

**Comment by FamousMai** [comment]
https://github.com/YFGaia/dify-plus/blob/main/docker/docker-compose.dify-plus.yaml

We provide a complete docker-compose file to start dify-plus with minimal dependencies, as shown above

If you still need to adjust according to your project situation, you can also refer to the docker-compose instructions of the original two projects
- https://gin-vue-admin.com/guide/deployment/docker-compose.html
- https://docs.dify.ai/zh-hans/getting-started/install-self-hosted/docker-compose

**Comment by FamousMai** [comment]
If the system you deploy is not arm64, you need to rebuild the following four images

- api
- web
- admin-web
- admin-server

Finally, modify your docker-compose file to reference the latest image you built locally

**Comment by jitangshaobing** [comment]
/app/service/gaia/account.go:79 ERROR: relation "accounts" does not exist (SQLSTATE 42P01)

**Comment by jitangshaobing** [comment]
After deployment, it seems that the initial data was not generated, only the table structure was initialized.
![Uploading 截屏2024-12-24 17.52.58.png…]()

**Comment by FamousMai** [comment]
Your picture cant open. Init data you can see the readme

https://github.com/YFGaia/dify-plus?tab=readme-ov-file#%E5%88%9D%E5%A7%8B%E5%8C%96%E7%AE%A1%E7%90%86%E5%91%98%E8%B4%A6%E5%8F%B7

**Comment by jitangshaobing** [comment]
![Uploading 截屏2024-12-24 17.52.58.png…]()

**Comment by jitangshaobing** [comment]
<img width="1309" alt="12" src="https://github.com/user-attachments/assets/8ca625ba-47a8-4732-a0b2-4746d5a7bc94" />

**Comment by jitangshaobing** [comment]
I have followed the initialization steps described in the README, but only the table structure is found in the database.

**Comment by jitangshaobing** [comment]
Can I exchange WeChat with you?

**Comment by FamousMai** [comment]
Yes！My wechat：famousmai
